version: "3.8"

services:
  hydra-db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: hydrapassword
      POSTGRES_USER: hydra
      POSTGRES_DB: hydra
    networks:
      - intranet

  hydra:
    image: oryd/hydra:v1.9.0-alpha.3
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
      - "5555:5555" # Port for hydra token user
    command:
      serve all --dangerous-force-http
    environment:
      - DSN=postgres://hydra:hydrapassword@hydra-db:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
      - SECRETS_SYSTEM=ZXhhbXBsZS1hcHAtc2VjcmV0
      - URLS_SELF_ISSUER=http://0.0.0.0:4444/
      - URLS_CONSENT=http://0.0.0.0:8001/consent
      - URLS_LOGIN=http://0.0.0.0:8001/login
      - SERVE_COOKIES_SAME_SITE_MODE=Lax
      - WEBFINGER_OIDC_DISCOVERY_SUPPORTED_SCOPE=email,name,groups
    restart: unless-stopped
    depends_on:
      - hydra-migrate
    networks:
      - intranet

  hydra-migrate:
    image: oryd/hydra:v1.9.0-alpha.3
    environment:
      - DSN=postgres://hydra:hydrapassword@hydra-db:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    command:
      migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet

  hydra-create-client:
    image: oryd/hydra:v1.9.0-alpha.3
    depends_on:
      - hydra
    command: clients create -n "Linnify App" --endpoint http://hydra:4445 --id linnify-app --secret LinnifySecret --grant-types authorization_code --response-types code --scope openid,email,name,groups,offline_access --token-endpoint-auth-method client_secret_post --callbacks "http://127.0.0.1:8000/auth/callback,http://127.0.0.1:8000/docs/oauth2-redirect"
    networks:
      - intranet

  auth:
    build:
      dockerfile: ./Dockerfile
      context: ./auth
    networks:
      intranet:
    ports:
      - 8001:8001

  api:
    build:
      dockerfile: ./Dockerfile
      context: ./backend
    env_file:
      - ./backend/.env
    networks:
      intranet:
    ports:
      - 8000:8000

  web:
    build:
      dockerfile: ./Dockerfile
      context: ./web
    networks:
      intranet:
    ports:
      - 3000:3000

networks:
  intranet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/16
          gateway: 172.31.0.1
